name: Divvy Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 55154
          script: |
            set -e

            echo "Pulling Repository"
            git config --global --add safe.directory /home/maman/Divvy

            cd /home/maman/Divvy
            git fetch origin 
            git reset --hard origin/main
            git clean -fd
            cd /var/www/projects/Divvy
            docker-compose up --build -d
            
      - name: Show Logs
        if: failure()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 55154
          script: |
            cd /var/www/projects/Divvy
            docker-compose logs --tail=100
