name: Divvy Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  


jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 55154
          script: |
            set -e

            id

            echo "Pulling Repository"
            git config --global --add safe.directory /var/www/projects/Divvy

            cd /var/www/projects/Divvy
            git fetch origin 
            git reset --hard origin/main
            git clean -fd

            DIVVY_API=divvy-api
            DB_DIVVY=db-divvy

            if [ "$(docker ps -q -f name=$DIVVY_API)" ] && [ "$(docker ps -q -f name=$DB_DIVVY)" ]; then
                echo "Kedua container ada dan sedang jalan. Restart stack..."
                docker-compose down -v
                docker-compose build
                docker-compose up -d
            else
                echo "Salah satu container belum ada/jalan. Build & up biasa..."
                docker-compose build
                docker-compose up -d
            fi


            
      - name: Show Logs
        if: failure()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 55154
          script: |
            cd /var/www/projects/Divvy
            docker-compose logs --tail=100
